/**
 * Single source of truth for the ForgetMeNot runtime version.
 *
 * Auto-generated by scripts/build-exe.mjs from package.json on every
 * build. Do NOT edit this file by hand — bump package.json and the
 * next build will regenerate. The committed value exists so `tsx watch`
 * dev mode has something to read without running a build first.
 */
export const VERSION = "0.1.49";
